- name: Install database dependencies
  apt: name='{{ item }}' state=present
  with_items:
   - mysql-server
   - mysql-client

- name: Start mysql service
  command: service mysql start

- name: Create mysql db
  mysql_db: 
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Initialize database
  mysql_query:
    login_db: "{{ db_name }}"
    query:
     - "CREATE TABLE IF NOT EXISTS {{ db_table }} (name VARCHAR(20) UNIQUE);"
     - "INSERT IGNORE INTO employees VALUES ('{{ employee_name }}');"
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create mysql user
  mysql_user: 
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    priv: '*.*:ALL'
    host: '%'
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

