- name: Deploy a flask web application
  hosts: node1,node2
 
  tasks:
   - name: Ping
     ping:

   - name: Install python dependencies
     apt: name='{{ item }}' state=present
     with_items:
      - python3 
      - python3-setuptools 
      - python3-dev
      - build-essential 
      - python3-pip
      - python3-mysqldb

   - include_tasks: tasks/deploy-db.yaml

   - include_tasks: tasks/deploy-flask.yaml

