- name: Deploy a flask web application
  hosts: node2
  tasks:
   - name: Ping
     ping:

   - name: Install python dependencies
     apt: name='{{ item }}' state=present
     with_items:
      - python3 
      - python3-setuptools 
      - python3-dev
      - build-essential 
      - python3-pip
      - python3-mysqldb

   - name: Install database dependencies
     apt: name='{{ item }}' state=present
     with_items:
      - mysql-server
      - mysql-client

   - name: Start mysql service
     command: service mysql start

   - name: Create mysql db
     mysql_db: 
       name: employee_db
       state: present
       login_unix_socket: /run/mysqld/mysqld.sock

   - name: Initialize database
     mysql_query:
       login_db: employee_db
       query:
        - CREATE TABLE IF NOT EXISTS employees (name VARCHAR(20) UNIQUE);
        - INSERT IGNORE INTO employees VALUES ('John Doe');
       login_unix_socket: /run/mysqld/mysqld.sock

   - name: Create mysql user
     mysql_user: 
       name: db_user
       password: Passw0rd
       priv: '*.*:ALL'
       host: '%'
       state: present
       login_unix_socket: /run/mysqld/mysqld.sock

   - name: Install python dependencies
     pip: 
      name: "{{ item }}"
      state: present
     with_items:
      - Werkzeug==2.2.2
      - Flask==2.1.3
      - Flask-MySQL==1.5.2
      - cryptography==42.0.5

   - name: Copy source code
     copy: 
      src: app.py
      dest: /opt/app.py

   - name: Start the web service
     shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &











